### ISSUE TITLE
everything works but their are no weapons

### ISSUE THREAD

**Issue by breakdowngamesYT** [Blixibon/css_weapons_in_hl2#2]

**Comment by breakdowngamesYT** [comment]
thier is no weapons in the code
and thier is no avalable counter strike source source code

**Comment by Blixibon** [comment]
Did you look at the "Code" section of the README?

**Comment by breakdowngamesYT** [comment]
yes
i found no weapons in your source sdk fork

**Comment by breakdowngamesYT** [comment]
i fixed it thier in shared
