### ISSUE TITLE
merged code issue

### ISSUE THREAD

**Issue by breakdowngamesYT** [Blixibon/css_weapons_in_hl2#4]
i merged the code and now sprinting speeds up falling and is to faster than normal witch file should i revert to fix this

yes my fork is mapbase

**Comment by Blixibon** [comment]
The CS:S weapons demo that comes with this fork has its own sped-up sprinting to help players get around. Are you experiencing this on any map beyond that one?

**Comment by breakdowngamesYT** [comment]
no i just thought it was wierd
